# Generated by Django 3.0.8 on 2020-10-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='../../static/facebook/img/avatars/default.jpg'),
        ),
    ]
