# Generated by Django 3.0.8 on 2020-10-14 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20201014_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
    ]
