# Generated by Django 3.0.8 on 2020-10-22 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0002_auto_20201021_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='friends_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='requesting',
            field=models.ManyToManyField(related_name='requesting_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
