# Generated by Django 3.0.8 on 2020-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_auto_20201024_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='comment_id', to='facebook.Comment'),
        ),
    ]
