# Generated by Django 3.0.8 on 2020-10-25 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20201024_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
