# Generated by Django 3.0.8 on 2020-10-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0010_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
